export default {
  FETCH_NOTES_REQUEST: 'FETCH_NOTES_REQUEST',
  NOTES_FETCH_SUCCESS: 'NOTES_FETCH_SUCCESS',
  NOTES_FETCH_ERROR: 'NOTES_FETCH_ERROR',

  SELECT_NOTE_REQUEST: 'SELECT_NOTE_REQUEST',
  SELECT_NOTE: 'SELECT_NOTE',

  FETCH_NOTE_REQUEST: 'FETCH_NOTE_REQUEST',
  NOTE_FETCH_SUCCESS: 'NOTE_FETCH_SUCCESS',
  NOTE_FETCH_ERROR: 'NOTE_FETCH_ERROR',

  NEW_NOTE_REQUEST: 'NEW_NOTE_REQUEST',
  NEW_NOTE_SUCCESS: 'NEW_NOTE_SUCCESS',
  NEW_NOTE_ERROR: 'NEW_NOTE_ERROR',

  UPDATE_NOTE_REQUEST: 'UPDATE_NOTE_REQUEST',
  UPDATE_NOTE_SUCCESS: 'UPDATE_NOTE_SUCCESS',
  UPDATE_NOTE_ERROR: 'UPDATE_NOTE_ERROR',

  REMOVE_NOTE_REQUEST: 'REMOVE_NOTE_REQUEST',
  REMOVE_NOTE_SUCCESS: 'REMOVE_NOTE_SUCCESS',
  REMOVE_NOTE_ERROR: 'REMOVE_NOTE_ERROR',
};
